### ISSUE TITLE
Non-Toolbox support

### ISSUE THREAD

**Issue by jrr** [RendleLabs/dotnet-rider-cli#4]
I haven't investigated this at all yet, but I suspect the problem is that I have an individually-installed Rider, rather than using Toolbox.

I ran e.g. `rider foo.sln`, and got the following stack trace:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at RiderLauncher.ToolboxRiderFinder.GetActiveExecutables()+MoveNext() in C:\Labs\rider\dotnet-rider-cli\src\RiderLauncher\ToolboxRiderFinder.cs:line 27
   at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at RiderLauncher.ToolboxRiderFinder.TryGetLatestActiveExecutable(String& path) in C:\Labs\rider\dotnet-rider-cli\src\RiderLauncher\ToolboxRiderFinder.cs:line 17
   at RiderLauncher.Program.Main(String[] args) in C:\Labs\rider\dotnet-rider-cli\src\RiderLauncher\Program.cs:line 19
```

**Comment by russcam** [comment]
Experienced the same issue. It looks like it's that the following file does not exist: 

https://github.com/RendleLabs/dotnet-rider-cli/blob/560297e1cb1000740a6f43ee719dce84d05a8d62/src/RiderLauncher/ToolboxRiderFinder.cs#L55-L58

**Comment by ThatRendle** [comment]
OK, I'll see what I can do.

**Comment by ThatRendle** [comment]
Although you should totally use Toolbox :)
